model_type: keyphrase
#tgt_type: verbatim_append
tht_type: random

data: data/keyphrase/meng17/sbset
# data: data/keyphrase/meng17/sbset_small
#data: data/keyphrase/meng17/stackexchange
save_checkpoint_steps: 500
keep_checkpoint: 1000
seed: 3435
train_steps: 50000
valid_steps: 500 # no validation
report_every: 100

encoder_type: brnn
rnn_type: GRU
word_vec_size: 100
rnn_size: 150
layers: 1

optim: adam
learning_rate: 1e-3
max_grad_norm: 2

batch_size: 64
valid_batch_size: 128
dropout: 0.1

global_attention: mlp

tensorboard: 'true'
log_file_level: DEBUG

copy_attn: 'true'
reuse_copy_attn: 'true'
coverage_attn: 'true'

context_gate: 'both'
input_feed: 1
share_embeddings: 'true'
bridge: 'true'

orth_reg: 'true'
lambda_orth_reg: 0.1
sem_cov: 'true'
lambda_sem_cov: 0.1

tgt_enc: 'rnn'
detach_tgt_enc: 'true'
num_negsample: 16
use_ending_state: 'true'

exp: sbset-one2seq-birnn-GRU150-EMB100-ATTNmlp-Dropout00
save_model: models/keyphrase/meng17-one2seq/sbset.one2seq.birnn.Dropout00
log_file: output/keyphrase/meng17-one2seq/sbset.one2seq.birnn.Dropout00.log
tensorboard_log_dir: runs/keyphrase/meng17-one2seq/sbset.one2seq.birnn.Dropout00/

world_size: 1
gpu_ranks: [0]
#- 0
#- 1
master_port: 5000

#train_from: models/keyphrase/meng17-one2seq-kp20k-topmodels/kp20k-meng17-no_sort-rnn-BS64-LR0.05-Layer1-Dim150-Emb100-Dropout0.0-Copytrue-Reusetrue-Covtrue-PEfalse-Contboth-IF1_step_90000.pt